title: Hojoon Kim
logo: /assets/img/Hojoon-Birthday.jpg
email: hojoonkim.02@gmail.com
description: RTOS Developer @ RTST <br> CS Undergraduate @ KAIST
url: https://kim-hojoon.github.io
favicon: true
# color-scheme: auto
google_analytics: G-WCHGK3L6Q9

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gist
  - jemoji

platforms:
  - name: Email
    icon: <i class="fa-regular fa-envelope"></i>
    link: mailto:hojoonkim.02@gmail.com
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/kim-hojoon
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/kim-hojoon
  - name: CV
    icon: <i class="ai ai-cv big-icon"></i>
    link: /assets/cv.pdf

navigation:
  - name: About Me
    link: ./index.html
    # sublist:
    #   - name: Image
    #     link: ./index.html#small-image
  # - name: Projects
  #   link: ./projects.html
